# Py_DECREF on a non-owned object in the _sre module

## Report Details
- **Report ID**: 159693
- **URL**: https://hackerone.com/reports/159693
- **State**: Closed
- **Severity**: N/A
- **Submitted**: 2016-08-16T09:34:14.241Z
- **Disclosed**: 2019-11-12T09:01:58.812Z

## Reporter
- **Username**: tehybel
- **Name**: N/A

## Team
- **Name**: N/A
- **Handle**: ibb

## Vulnerability Information
I described this vulnerability in detail in a mail to the PSRT. A copy of my email, plus the fix for this issue, can be found here:

https://bugs.python.org/issue27774

## Attachments
No attachments
